### ISSUE TITLE
Apollo LM antenna and iva bug

### ISSUE THREAD

**Issue by Ilikeflyingplanes1** [KSP-RO/ROCapsules#11]
The HGA on the lm does not work with remote tech so far, there is no option to connect to a ground station, and the buttons are slightly broken Also the iva cabin is backwards from the spacecraft
![screenshot997](https://user-images.githubusercontent.com/53797722/64071098-bd238500-cc37-11e9-8e4b-70afc6ede2ea.png)

**Comment by DRVeyl** [comment]
Fixed and merged with https://github.com/KSP-RO/ROCapsules/pull/26
