### ISSUE TITLE
Voskhod Airlock uses position as height?

### ISSUE THREAD

**Issue by lpgagnon** [KSP-RO/ROCapsules#12]
Placing the ROC-VoskhodAirlock on a craft sets the craft's height (per VAB engineer's report) roughly equal to the airlock's position in the VAB, instead of just taking the part's height into account. An airlock near the floor gives a height of a couple of meters; an airlock near the ceiling gives a height of ~50m.

**Comment by vader111** [comment]
Might be fixed with https://github.com/KSP-RO/ROCapsules/pull/72 i will have to test
