### ISSUE TITLE
Apollo CM crashes game when launching or simulating

### ISSUE THREAD

**Issue by internetboyfriend666** [KSP-RO/ROCapsules#134]
The ROcapsules Apollo parts crashes the game when I go to launch or simulate. It's all the various ROCapsules Apollo parts but *no* other game parts. 

Log here: https://www.dropbox.com/s/jkn5juj8sey7vkg/Player.log.zip?dl=0

I'm playing on macOS 12.6.1. KSP is 1.12.3, install is correct via CKAN Express install.

**Comment by Capkirk123** [comment]
This should have been resolved by switching the Apollo model to the one provided by BDB

**Comment by internetboyfriend666** [comment]
Sorry this was resolved months ago not sure why it wasn't marked as such
