### ISSUE TITLE
D-2 Probe or Apollo Probe has incorrect unlock requirements

### ISSUE THREAD

**Issue by Clayell** [KSP-RO/ROCapsules#140]
I'm not sure which one is incorrect, but there's a problem here. 
The D-2 Docking Probe requires "ROC-D2DockProbe" (4000) and "D2Dock" (57000) unlock requirements, which costs 61000 funds in total.
The Apollo Docking Mechanism Probe requires "ROC-ApolloProbeDockPortBDB" (0), "dockingApollo" (55000), and "capsulesApollo" (420000), which costs 475000 funds in total.
Considering these two probes unlock at the same tech level and are both for similar, I would not expect their unlock requirements to be so different, so either one of these should be fixed to represent the usual amount.

Pictures: 
[D-2 Docking Probe](https://cdn.discordapp.com/attachments/617156220146417664/1102678039533465620/image.png)
[Apollo Docking Mechanism Probe](https://cdn.discordapp.com/attachments/617156220146417664/1102678068725821461/image.png)

**Comment by NathanKell** [comment]
This is an RP-1 issue, not a ROC issue. But as you mention in your text, the D-2 ECMs do not include the ECM for the capsule itself, it looks like.

**Comment by Clayell** [comment]
Noted, will notify them
