### ISSUE TITLE
Gemini capsule and service module present the wrong diameters

### ISSUE THREAD

**Issue by ProtonEnjoyer** [KSP-RO/ROCapsules#141]
The real life Gemini was 10ft in diameter, the same diameter as the Titan II GLV rocket and Atlas rocket.
However, turns out that in ROCapsules, Gemini displays the wrong diameter (2.84m instead of 3.05m), which is incorrect.

It is not a game breaking issue, but it does follow quite a decent amount of innacuracies.
![image](https://user-images.githubusercontent.com/47197588/236704171-39ae18ce-47cd-4b58-aeab-9a6d685e0c22.png)
(Centaur below for scale)

**Comment by Capkirk123** [comment]
This is an unfortunate consequence of the original BDB part being scaled to stock diameters. It was chosen to have the Gemini capsule itself be the correct diameter, rather than the service module.
