### ISSUE TITLE
Incorrect Gemini Dimensions

### ISSUE THREAD

**Issue by MichaelPetch** [KSP-RO/ROCapsules#165]
The Gemini Equipment section & Retrograde section that are enabled by default in the realism overhaul career mode tech tree have incorrect dimensions for mating to the Titan II GLV, I noticed this while trying to replicate the rocket in my own career mode. The bottom dimensions on the Gemini Equipment section are 2.85m where they should be 3.048m, this change would most likely throw off all of the parts however. 
![image](https://github.com/KSP-RO/ROCapsules/assets/44859360/efc7d277-18f1-4944-87af-d4fdd9952e12)

**Comment by lpgagnon** [comment]
#141
