### ISSUE TITLE
Add support for RealAntenna to the Apollo HGA

### ISSUE THREAD

**Issue by kurgut** [KSP-RO/ROCapsules#2]
Basically, would need to add this in ApolloHGA .cfg
`	MODULE:NEEDS[RealAntennas]
	{
		name = ModuleRealAntenna
		antennaDiameter = 0.78
		RFband = S
	}`
but this doesn't delete the existing [moduledatatransmitter] added in the same .cfg, which I can't figure out how to get rid off, mostly due to my high MM skills..

**Comment by DRVeyl** [comment]
Completed in https://github.com/KSP-RO/ROCapsules/commit/734608376d5ff6e27a11fffc439ccc63bec068bd
