### ISSUE TITLE
APAS 89/95 doesn't dock nor undock

### ISSUE THREAD

**Issue by lipo842** [KSP-RO/ROCapsules#28]
Neither APAS 89/95 active or passive docking port have the ability to dock to each other, nor undock when connected in VAB. No magnetism, no Control From Here button, no docking even after a precise alignment. RP-1 station contracts don't read them as docking port.
![screenshot72](https://user-images.githubusercontent.com/45542717/81540323-c42b9700-9371-11ea-9019-3f10127e3571.png)

**Comment by DRVeyl** [comment]
Fixed with https://github.com/KSP-RO/ROCapsules/pull/30
