### ISSUE TITLE
1.2.0 Mercury Capsule missing CO2 scrubbing

### ISSUE THREAD

**Issue by willclemmer** [KSP-RO/ROCapsules#45]
I noticed the new update because the previous version of the Mercury capsule (with integrated heatshield) could no longer safely re-enter.  I've switched to the new Mercury capsule but noticed this one doesn't include CO2 scrubbing, so missions are limited to just an hour or two.  Maybe this is intentional?  But I assume it's just an oversight.

I looked at the config file vs. the previous release and it has the same LiOH scrubber config.  Not sure why it's not showing up in the editor.  Config note: I'm using Kerbalism rather than TAC Life Support, but even though this section is tagged TAC-LS the previous Mercury pod was able to pick up the CO2 scrubber

**Comment by Standecco** [comment]
Fixed in ROKerbalism master, will be included in the next release. 
You could pull the latest changes but they will break any vessel with Shielding (should be fine if it had 0) already in flight, so watch out for that.

**Comment by willclemmer** [comment]
Fix confirmed. Thanks Standecco!
