### ISSUE TITLE
1.2.0 Mercury capsules overheat

### ISSUE THREAD

**Issue by willclemmer** [KSP-RO/ROCapsules#46]
Mercury capsules seem much more fragile: standard reentry burning retro rockets from 200km experiences thermal failure unless Deadly Reentry (Maat edition) thermal physics are turned down to 80% or so.  Reentry is possible by adding non-historical additional retro rockets, additional heat shields etc. but 1962 Mercury-Atlas replicas using this model aren't able to survive missions like Mercury-Atlas 6 (apogee 248km, perigee 150km) without modifying physics.  

Notes: 
* This issue seems to have appeared in the last 2 weeks: returns from 300km were working prior to this
* This seems to be occurring with the new Mercury (with the separate heatshield) but also when reverting back to older versions of ROCapsules to use the previous integrated-shield version.  So the issue may come from another mod.  I've done a clean RP-1 install to test local configuration and have the same behavior in the clean install

**Comment by Standecco** [comment]
Most likely caused by the new changes in FAR (@DRVeyl could confirm this). Reentry is still possible, but you have to do it with historic parameters now: a -150km (yep, negative) perigee is needed to avoid burning up.

**Comment by willclemmer** [comment]
Thanks Standecco!  I appreciate your help (and am amazed at the excellent work you're all doing on this project!)

I agree with you but confirm that even with retro perigee of -300k or so from LEO I still get fatal overheating.  Please see attached for initial orbit (Mercury-Atlas 6 approximation, apo 259k, peri 150k), post retro (apo  145k, peri -295k), and subsequent unplanned disassembly.

One important note: this applies to *production launches only*.  When I test the same rocket in TestFlight (even right before actual launch) the physics are different: I can safely return from a 300k circular orbit using the same craft.  I'm not sure what in the game is making production physics different from TestFlight physics, but I've done a clean reinstall of RP-1 and am getting the same behavior.  

The workaround so far is to reduce Re-Entry Heating in Deadly Reentry to 75%.  With this modification I can safely return from otherwise-historical orbital missions with a ~250km apogee.  I hope this is helpful!

![46_1_before_retro](https://user-images.githubusercontent.com/60412645/91882794-595fdd80-ec38-11ea-9bac-c857c07efbe8.png)
![46_2_after_retro](https://user-images.githubusercontent.com/60412645/91882836-67adf980-ec38-11ea-9267-a7045ed17012.png)
![46_3_initial_reentry](https://user-images.githubusercontent.com/60412645/91882857-7399bb80-ec38-11ea-9e18-8e9b27a59a82.png)
![46_4_overheating](https://user-images.githubusercontent.com/60412645/91882887-7eece700-ec38-11ea-82cd-722b306b5bb2.png)
![46_5_critical_overheating](https://user-images.githubusercontent.com/60412645/91882925-8ad8a900-ec38-11ea-9d1a-3fbcb52d2c8e.png)
![46_6_boom](https://user-images.githubusercontent.com/60412645/91882962-975d0180-ec38-11ea-9890-aa4aa09c8fde.png)
![46_7_aftermath](https://user-images.githubusercontent.com/60412645/91882984-a0e66980-ec38-11ea-95c1-5f04e9c17555.png)

**Comment by pap1723** [comment]
The new Mercury Capsule needs the Mercury Heatshield. As you can see, you have no Ablator.

**Comment by willclemmer** [comment]
Thanks pap1723!  Good point, though in this craft the Mercury Heatshield is actually installed: please see attached screenshot.  I noticed that in this version neither the Mercury Heatshield nor the Gemini Heatshield had Ablator (or a sink for CharredAblator) but assumed that this meant that the new models used some mechanism other than Ablator for re-entry.  So the lack of Ablator on the Heatshield part may be the answer.

![screenshot104](https://user-images.githubusercontent.com/60412645/91916420-f5f2a180-ec71-11ea-8140-1361fe4b0e5a.png)

**Comment by pap1723** [comment]
Pull the trigger on master version of ROCapsules.

**Comment by willclemmer** [comment]
Thanks pap1723!  Downloaded master version of ROCapsules from the GitHub link https://github.com/KSP-RO/ROCapsules.git.  (Downloaded ZIP, timestamp inside the ZIP is 2020-08-10 18:01).  Closed KSP, deleted previous ROCapsules directory and replaced with the GameData\ROCapsules in the ZIP file.

Ablator resource still not appearing on the Mercury Heatshield (see screenshot attached, along with stock heatshield example where Ablator is visible).  In case there's a tech tree unlock which grants this resource, including a snapshot of the Tech Tree also.

![screenshot105](https://user-images.githubusercontent.com/60412645/91918206-238e1980-ec77-11ea-8049-ba6a42ca5f4c.png)
![screenshot106](https://user-images.githubusercontent.com/60412645/91918246-415b7e80-ec77-11ea-883b-9a0a6a11f384.png)
![screenshot107](https://user-images.githubusercontent.com/60412645/91918475-d199c380-ec77-11ea-80bc-c46b67007f78.png)

**Comment by Capkirk123** [comment]
You need RO master for the heatshields to work.

**Comment by willclemmer** [comment]
Thanks Capkirk123!  I assume you mean I need to pull the master branch of Realism Overhaul, not just the Master branch of ROCapsules (which I believe I'm correctly pulling, see screenshot below).  I'll go get that and see if it resolves.  Thanks!

![Screenshot from 2020-09-01 17-34-12](https://user-images.githubusercontent.com/60412645/91919182-ef682800-ec79-11ea-815a-81ac640ad210.png)

**Comment by willclemmer** [comment]
Winner winner chicken dinner!!!  :-)  Thanks much Capkirk123!  I confirm that pulling the latest RO Master from https://github.com/KSP-RO/RealismOverhaul.git adds Ablator and a CharredAblator sink to the Mercury Heatshield.  I'll run through the previous tests to confirm whether this fixes all the behavior in the reported issue.

**Comment by willclemmer** [comment]
I confirm that with this fix, production Mercury capsules now pass reentry tests from the 200km apogee range (just barely ^_^, but this seems historically accurate). Thanks everyone for your help!  I'll close the issue now.  For debugging purposes, prior to these pulls I've been getting my versions through CKAN, so it's possible CKAN is picking up the latest ROCapsules but not the latest RealismOverhaul.

![screenshot111](https://user-images.githubusercontent.com/60412645/91922865-e1b7a000-ec83-11ea-9a2c-47735d42234d.png)
![screenshot113](https://user-images.githubusercontent.com/60412645/91922898-f1cf7f80-ec83-11ea-85be-8931ddd385d4.png)
