### ISSUE TITLE
No Kerbalism in latest relase

### ISSUE THREAD

**Issue by bweickert** [KSP-RO/ROCapsules#51]
Hey,

the newest release does not work with kerbalism. You don't have any possibility to get rid of the co2 in the capsule and the kerbals are dying slowly . 

Great mod btw!

**Comment by pap1723** [comment]
This is actually the proper functionality.

**Comment by lpgagnon** [comment]
no it's not. the new Mercury and Gemini have no scrubber in the latest ROKerbalism release; only ROKerbalism's master branch has the needed configs
