### ISSUE TITLE
ROC Dequ Apollo CSM and LRV animations/actions gone in the master branch

### ISSUE THREAD

**Issue by Jeceratops** [KSP-RO/ROCapsules#57]
This is a weird bug, the LRV cant fold up, the CSM cant close/ open its sub-satellite bay, and the apollo docking mechanism extending animation is broken on the forwards heatshied, the other parts seem fine

**Comment by Jeceratops** [comment]
Here are the examples 
![image](https://user-images.githubusercontent.com/69649180/94315914-6f1fa480-ff51-11ea-9cca-a77faf88ba92.png)
![image](https://user-images.githubusercontent.com/69649180/94315924-734bc200-ff51-11ea-8b0b-1b0d307aedb7.png)
![image](https://user-images.githubusercontent.com/69649180/94316163-dfc6c100-ff51-11ea-8d77-87c71daaabfd.png)
![image](https://user-images.githubusercontent.com/69649180/94316375-359b6900-ff52-11ea-967b-fd03567cc24f.png)

**Comment by SlapheadSte** [comment]
You need KSP Wheel to have the rover deployment animation.

**Comment by Capkirk123** [comment]
Cannot reproduce? And moot anyway, given https://github.com/KSP-RO/ROCapsules/pull/132 supersedes DECQ Apollo parts.
