### ISSUE TITLE
DECQ Apollo CM +p RCS thrusters are angled through the CoM

### ISSUE THREAD

**Issue by gazpachian** [KSP-RO/ROCapsules#7]
The net result is that pitch up commands have about 1/10th the effect of pitch down, or any other attitude adjustment for that matter. The issue pertains not only to ROCapsules but to DECQ's base mod as well. I've contacted DECQ about the issue via the forums and I await a reply. However, they have not been online since october of last year so I think the best course of action is to correct the issues ourselves.

I tried hacking a fix myself but I could not get it to work without accidentally removing the ability to EVA. If there is someone more experienced with .mu file authoring around here (which I deem to be very likely) fixing the thrusters without borking the part should be simple. Illustration for clarity:
![Screenshot from 2019-08-09 16-05-30](https://user-images.githubusercontent.com/3220774/62786669-5e993a00-bac3-11e9-8cc3-aaa798603467.png)

**Comment by DRVeyl** [comment]
Does <https://github.com/KSP-RO/ROCapsules/commit/8a9f0a5bf4c39099e0b1c093e5682239fe11ae6c> address?

Not sure where we have the model expertise here, either.  Has the original model source gotten an update?

**Comment by gazpachian** [comment]
I unfortunately haven't got a working RSS installation to test this out, but the patch does adress this very issue (if perhaps in a work-aroundish way). The original author has yet to respond to my suggestion on the forums so we should probably treat him as entirely MIA. I suggest keeping this issue open in case someone with more .mu tweaking experience stumbles across this thread and wants to have a go at it, but it is now of a lower priority given the fix provided by [8a9f0a5](https://github.com/KSP-RO/ROCapsules/commit/8a9f0a5bf4c39099e0b1c093e5682239fe11ae6c).

**Comment by lpgagnon** [comment]
As the commit message indicates, 8a9f0a5 mitigates the problem, but it's definitely still a problem worth fixing (unless the current thrust direction is actually deliberate/historically accurate)

**Comment by gazpachian** [comment]
Back when I opened this issue I did my best to research if it was historically accurate by digging into NASA:s NTR archives, but I could not find any mention of a torque descripancy between positive and negative pitch for the Apollo CM. Short of asking an actual astronaut if they recall that being the case (perhaps we should?) I think we can assume that there should not be such a big difference (without your patch I think the difference was something like 13:1?) without the technical manuals mentioning that fact.

**Comment by Capkirk123** [comment]
Resolved by https://github.com/KSP-RO/ROCapsules/pull/132, seeing as the DECQ Apollo CM is no longer used.
