### ISSUE TITLE
Mercury and Apollo + Lander's attachment nodes are not 'rigid'

### ISSUE THREAD

**Issue by daantimmer** [KSP-RO/ROCapsules#74]
Essentially the Mercury + attached nodes all bend under the stress of dynamic forces. When time warping this deformation of the parts is more pronounced. I've tried launching with and without the heatshield, LEM and retropack. None of these make a difference.

The same happens with the Apollo and Lander parts.

Example of the Apollo behaviour: 
![screenshot43](https://user-images.githubusercontent.com/8293597/99157975-05f51b80-26ce-11eb-989a-3a9c737502a5.jpg)

The Gemini capsule has no issues whatsoever.

**Comment by daantimmer** [comment]
Here is an example where I was experimenting if it had to do with a specific node of the Mercury parts:
https://www.youtube.com/watch?v=3AtjrQi358c&ab_channel=Ashnoom

**Comment by daantimmer** [comment]
Here is an example of a normal Mercury launch (with some closeup examples, showcasing the issue, and some bad camera work, sorry for that). https://www.youtube.com/watch?v=uvNma4DNkdM&ab_channel=Ashnoom

**Comment by daantimmer** [comment]
As per a bit more testing it could potentionally (for the Mercury) be the Heatshield that is causing an issue. I just replaced the capsule with a procedural avionics replica (same dimensions+weight) which was also exerting the issue. Then I removed the heatshield and the issue was gone.

**Comment by Capkirk123** [comment]
This is a known issue caused by animated attachment/animated decouplers. Remove those mods and see if you can reproduce.

**Comment by daantimmer** [comment]
@Capkirk123 I  had found this out already indeed. Forgotten that I had an issue open.

Perhaps this is a case of 'mark as incompatible' in CKAN? Or is that something for the KJR mod?
