### ISSUE TITLE
Lunar Module's docking lights grow in size during flashing.

### ISSUE THREAD

**Issue by SlapheadSte** [KSP-RO/ROCapsules#76]
This is a bug that has been prevelent before the recent patch. Cabin lights on the Lunar Module ascent stage grow in size during its flashing animation and looks super odd during capture. Turning on "Activate docking lights" results in the same effect except it stays.

![image](https://user-images.githubusercontent.com/24409288/99911911-66e4ab00-2cef-11eb-8d6e-a4ba39d2b8d2.png)
![image](https://user-images.githubusercontent.com/24409288/99912216-84b21000-2cef-11eb-8bc8-99d0a9375976.png)
![image](https://user-images.githubusercontent.com/24409288/99912611-a01d1b00-2cef-11eb-9eea-80e24464a912.png)

**Comment by Capkirk123** [comment]
Resolved by https://github.com/KSP-RO/ROCapsules/pull/132, seeing as DECQ models are no longer used.
