### ISSUE TITLE
Mercury capsule texture

### ISSUE THREAD

**Issue by Sebast0409** [KSP-RO/ROCapsules#79]
On the Mercury capsule, there are two textures overlapping causing a white/black flicker. I've tried deleting the Mercury White texture but its still showing up.
![Screenshot (4)](https://user-images.githubusercontent.com/78999794/107845103-5ff2a380-6dd9-11eb-8d64-2ae6e748e5f6.png)

**Comment by CobaltWolf** [comment]
It appears all the meshes are enabled - they're normally managed by a switcher. Is this behavior still happening?

**Comment by Capkirk123** [comment]
Do you have the correct version of B9 part switch installed? It is required for ROCapsules to function correctly
