### ISSUE TITLE
BoxCollider Issue with DECQ Models

### ISSUE THREAD

**Issue by DRVeyl** [KSP-RO/ROCapsules#81]
[WRN 18:38:35.640] BoxColliders does not support negative scale or size.
The effective box size has been forced positive and is likely to give unexpected collision geometry.
If you absolutely need to use negative scaling you can use the convex MeshCollider. Scene hierarchy path "ROC-ApolloCMBlockIII/ROC-ApolloHSBlockIII+/ROC-ApolloSMBlockIII/ROC-ApolloEngineBlockIII/ROC-LEMDescent/model/ROCapsules/Assets/DECQ/LEM/LEM_Descent(Clone)/1/LEM_STAGE1/NODE"

Also this when grabbing the Apollo LM Ascent Stage:

[ERR 18:42:03.029] [ModuleSrfFX]: No IThrustProvider module found at index 0!
	UnityEngine.DebugLogHandler:LogFormat(LogType, Object, String, Object[])
	ModuleManager.UnityLogHandle.InterceptLogHandler:LogFormat(LogType, Object, String, Object[])
	UnityEngine.Debug:LogError(Object, Object)
	ModuleSurfaceFX:Start()

On the Apollo rover:
[ERR 18:43:54.051] Cannot find fx group of that name for decoupler
	UnityEngine.DebugLogHandler:LogFormat(LogType, Object, String, Object[])
	ModuleManager.UnityLogHandle.InterceptLogHandler:LogFormat(LogType, Object, String, Object[])
	UnityEngine.Debug:LogError(Object)
	ModuleDecouplerBase:OnAwake()
	ModuleDecouple:OnAwake()
	PartModule:Awake()
	UnityEngine.GameObject:SetActive(Boolean)
	EditorLogic:SpawnPart(AvailablePart)
	EditorLogic:OnPartListIconTap(AvailablePart)
	KSP.UI.Screens.EditorPartList:TapIcon(AvailablePart)
	KSP.UI.Screens.EditorPartIcon:MouseInput_SpawnPart()
	UnityEngine.EventSystems.EventSystem:Update()

**Comment by Capkirk123** [comment]
Resolved by https://github.com/KSP-RO/ROCapsules/pull/132, seeing as DECQ models are no longer used.
