### ISSUE TITLE
Apollo RCS

### ISSUE THREAD

**Issue by NathanKell** [KSP-RO/ROCapsules#86]
As I understand it, while the LM used NTO/AZ50 because it shared tankage for RCS with the LMAE, the SM RCS was NTO/MMH. But the "Apollo SM RCS Block" - ROC-ApolloRCS - uses NTO and AZ50.

**Comment by NathanKell** [comment]
(Is my understanding incorrect? Or was this copypasta from the LM RCS?)

**Comment by Capkirk123** [comment]
As of https://github.com/KSP-RO/ROCapsules/pull/132 it used MMH/NTO, with O/F set based on the fuel loads of the Apollo RCS system as described in the PR.
