### ISSUE TITLE
Conic Cockpit (x-1) shows EVA mouseover even when mouse is nowhere near the craft

### ISSUE THREAD

**Issue by dgeastman** [KSP-RO/ROCapsules#94]
The recolorable X-1 cockpit (conic cockpit) has a weird issue where in flight, the mouseover check for the EVA hatch seems to have no boundaries, if the cursor is over anything other than another layer such as a mechjeb window or the navball, the EVA hatch mouseover text is present, and if you click, the EVA dialog spawns.

**Comment by Bornholio** [comment]
Confirm this, also IVA view is set behind cockpit so tank attached has its bulkhead blocking the forward view.

**Comment by lpgagnon** [comment]
x-1 cockpit lives in RO, not ROCapsules. https://github.com/KSP-RO/RealismOverhaul/issues/2466
