### ISSUE TITLE
D2 Apollo antennaDiameter

### ISSUE THREAD

**Issue by badgermasher** [KSP-RO/ROCapsules#97]
https://github.com/KSP-RO/ROCapsules/blob/d8d5bf7f0621f59857da9edd0a0b310f19b856c5/GameData/ROCapsules/PartConfigs/Apollo%20D2/D2Antenna.cfg#L124

The D2Antenna's RealAntenna config currently sets an antennaDiameter that does not match the model. The antennaDiameter should be set to match the actual part model's reflector diameter, which in this case appears to be slightly more than 0.6 meters. See the image linked below where I have done my best to match a procedural tank to the diameter of the reflector.

https://i.imgur.com/IqE9msy.png

My understanding is that this was copied from the Apollo HGA config which may have a related issue. Since that model has multiple  reflectors  the antennaDiameter should be set to the square root of the number of reflectors multiplied by the diameter of an individual reflector.

**Comment by NathanKell** [comment]
Regular Apollo HGA was fine, FYI.
